# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "hacklab.localdomain"
  config.vm.network :private_network, ip: "192.168.10.11"
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id,"--cpus","1",]
    vb.customize ["modifyvm", :id,"--memory", 512]
  end
end
