# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

domain   = '.hacklab.local'
nodes = [
  { :hostname => 'a1',      :ip => '192.168.10.11', :box => 'centos/7',  :ram => '512' },
  { :hostname => 'a2',      :ip => '192.168.10.12', :box => 'precise64', :ram => '512' },
]

Vagrant.configure("2") do |config|

  ### PUPPET SERVER
  config.vm.define "puppet" do |puppet|
    puppet.vm.box = "centos/7"
    puppet.vm.hostname = "server"
    puppet.vm.network :private_network, ip: "192.168.10.10"
    puppet.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", "512" ]
      v.customize ["modifyvm", :id, "--cpus", "1" ]
    end
    puppet.vm.provision :shell, :path => "bootstrap-puppetserver.sh"
  ### END PUPPET SERVER

  ### PUPPET AGENTS
    nodes.each do |node|
      config.vm.define node[:hostname] do |nodeconfig|
        nodeconfig.vm.box = node[:box]
        nodeconfig.vm.hostname = node[:hostname] + domain
        nodeconfig.vm.network :private_network, ip: node[:ip]
        nodeconfig.vm.provision :shell, :path => "bootstrap-puppetagent.sh"

        memory = node[:ram] ? node[:ram] : 256;
        nodeconfig.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id,"--cpus","1",]
          vb.customize ["modifyvm", :id,"--memory", memory.to_s,]
        end
      end
    end
  end
  ### END PUPPET AGENTS
end
